from pygments.lexer import RegexLexer, words, bygroups, using
from pygments.token import Token

import re
import copy

class BslLexer(RegexLexer):
    name = '1C (BSL) Lexer'
    aliases = ['bsl', 'os']
    filenames = ['*.bsl', '*.os']

    flags = re.MULTILINE | re.IGNORECASE | re.VERBOSE

    KEYWORD_DECLARATION = words((
        # storage.type.var.bsl
        'Перем','Var',
    ), prefix='(?<!\.)', suffix=r'\b')    

    KEYWORD = words((
        # storage.type.bsl
        'Процедура','Procedure','Функция','Function',
        # storage.modifier.bsl
        'Экспорт', 'Export',
        # storage.type.bsl
        'КонецПроцедуры','EndProcedure','КонецФункции','EndFunction',
        # keyword.control.bsl
        'Прервать','Break','Продолжить','Continue','Возврат','Return',
        # keyword.control.conditional.bsl
        'Если','If','Иначе','Else','ИначеЕсли','ElsIf',
        'Тогда','Then','КонецЕсли','EndIf',
        # keyword.control.exception.bsl
        'Попытка','Try','Исключение','Except',
        'КонецПопытки','EndTry',
        # keyword.control.repeat.bsl
        'Пока','While','Для','For','Каждого','Each',
        'Из','In','По','To','Цикл','Do','КонецЦикла', 'EndDo',
        # keyword.operator.logical.bsl
        'НЕ','NOT','И','AND','ИЛИ','OR',
        # support.function.bsl
        'Новый','New',
        # execute statement
        'Выполнить','Execute',
        # storage.modifier.bsl
        'Знач', 'Val',
        # 
        'Перейти', 'Goto',
        'Асинх', 'Async',
        'Ждать', 'Await',
    ), prefix='(?<!\.)', suffix=r'\b')
    
    NAME_BUILTIN = words((
        # support.function.bsl
        # Глобальный контекст - функции работы со значениями типа Строка
        'СтрДлина','StrLen',
        'СокрЛ','TrimL','СокрП','TrimR','СокрЛП','TrimAll',
        'Лев','Left','Прав','Right','Сред','Mid',
        'СтрНайти','StrFind',
        'ВРег','Upper','НРег','Lower','ТРег','Title',
        'Символ','Char','КодСимвола','CharCode',
        'ПустаяСтрока','IsBlankString',
        'СтрЗаменить','StrReplace',
        'СтрЧислоСтрок','StrLineCount',
        'СтрПолучитьСтроку','StrGetLine',
        'СтрЧислоВхождений','StrOccurrenceCount',
        'СтрСравнить','StrCompare',
        'СтрНачинаетсяС','StrStartWith',
        'СтрЗаканчиваетсяНа','StrEndsWith',
        'СтрРазделить','StrSplit',
        'СтрСоединить','StrConcat',
        # Глобальный контекст - функции работы со значениями типа Число
        'Цел','Int','Окр','Round',
        'ACos','ACos','ASin','ASin','ATan','ATan',
        'Cos','Cos','Exp','Exp','Log','Log','Log10','Log10',
        'Pow','Pow','Sin','Sin','Sqrt','Sqrt','Tan','Tan',
        # Глобальный контекст - функции работы со значениями типа Дата
        'Год','Year','Месяц','Month','День','Day',
        'Час','Hour','Минута','Minute','Секунда','Second',
        'НачалоГода','BegOfYear',
        'НачалоДня','BegOfDay',
        'НачалоКвартала','BegOfQuarter',
        'НачалоМесяца','BegOfMonth',
        'НачалоМинуты','BegOfMinute',
        'НачалоНедели','BegOfWeek',
        'НачалоЧаса','BegOfHour',
        'КонецГода','EndOfYear',
        'КонецДня','EndOfDay',
        'КонецКвартала','EndOfQuarter',
        'КонецМесяца','EndOfMonth',
        'КонецМинуты','EndOfMinute',
        'КонецНедели','EndOfWeek',
        'КонецЧаса','EndOfHour',
        'НеделяГода','WeekOfYear',
        'ДеньГода','DayOfYear',
        'ДеньНедели','WeekDay',
        'ТекущаяДата','CurrentDate',
        'ДобавитьМесяц','AddMonth',
        # Глобальный контекст - функции работы со значениями типа Тип
        'Тип','Type','ТипЗнч','TypeOf',
        # Глобальный контекст - функции преобразования значений
        'Булево','Boolean','Число','Number',
        'Строка','String','Дата','Date',
        # Глобальный контекст - процедуры и функции интерактивной работы
        'ПоказатьВопрос','ShowQueryBox',
        'Вопрос','DoQueryBox',
        'ПоказатьПредупреждение','ShowMessageBox',
        'Предупреждение','DoMessageBox',
        'Сообщить','Message',
        'ОчиститьСообщения','ClearMessages',
        'ОповеститьОбИзменении','NotifyChanged',
        'Состояние','Status',
        'Сигнал','Beep',
        'ПоказатьЗначение','ShowValue',
        'ОткрытьЗначение','OpenValue',
        'Оповестить','Notify',
        'ОбработкаПрерыванияПользователя','UserInterruptProcessing',
        'ОткрытьСодержаниеСправки','OpenHelpContent',
        'ОткрытьИндексСправки','OpenHelpIndex',
        'ОткрытьСправку','OpenHelp',
        'ПоказатьИнформациюОбОшибке','ShowErrorInfo',
        'КраткоеПредставлениеОшибки','BriefErrorDescription',
        'ПодробноеПредставлениеОшибки','DetailErrorDescription',
        'ПолучитьФорму','GetForm',
        'ЗакрытьСправку','CloseHelp',
        'ПоказатьОповещениеПользователя','ShowUserNotification',
        'ОткрытьФорму','OpenForm',
        'ОткрытьФормуМодально','OpenFormModal',
        'АктивноеОкно','ActiveWindow',
        'ВыполнитьОбработкуОповещения','ExecuteNotifyProcessing',
        # Глобальный контекст - функции для вызова диалога ввода данных
        'ПоказатьВводЗначения','ShowInputValue',
        'ВвестиЗначение','InputValue',
        'ПоказатьВводЧисла','ShowInputNumber',
        'ВвестиЧисло','InputNumber',
        'ПоказатьВводСтроки','ShowInputString',
        'ВвестиСтроку','InputString',
        'ПоказатьВводДаты','ShowInputDate',
        'ВвестиДату','InputDate',
        # Глобальный контекст - функции форматирования
        'Формат','Format',
        'ЧислоПрописью','NumberInWords',
        'НСтр','NStr',
        'ПредставлениеПериода','PeriodPresentation',
        'СтрШаблон','StrTemplate',
        # Глобальный контекст - функции обращения к конфигурации
        'ПолучитьОбщийМакет','GetCommonTemplate',
        'ПолучитьОбщуюФорму','GetCommonForm',
        'ПредопределенноеЗначение','PredefinedValue',
        'ПолучитьПолноеИмяПредопределенногоЗначения','GetPredefinedValueFullName',
        # Глобальный контекст - процедуры и функции сеанса работы
        'ПолучитьЗаголовокСистемы','GetCaption',
        'ПолучитьСкоростьКлиентскогоСоединения','GetClientConnectionSpeed',
        'ПодключитьОбработчикОжидания','AttachIdleHandler',
        'УстановитьЗаголовокСистемы','SetCaption',
        'ОтключитьОбработчикОжидания','DetachIdleHandler',
        'ИмяКомпьютера','ComputerName',
        'ЗавершитьРаботуСистемы','Exit',
        'ИмяПользователя','UserName',
        'ПрекратитьРаботуСистемы','Terminate',
        'ПолноеИмяПользователя','UserFullName',
        'ЗаблокироватьРаботуПользователя','LockApplication',
        'КаталогПрограммы','BinDir',
        'КаталогВременныхФайлов','TempFilesDir',
        'ПравоДоступа','AccessRight',
        'РольДоступна','IsInRole',
        'ТекущийЯзык','CurrentLanguage',
        'ТекущийКодЛокализации','CurrentLocaleCode',
        'СтрокаСоединенияИнформационнойБазы','InfoBaseConnectionString',
        'ПодключитьОбработчикОповещения','AttachNotificationHandler',
        'ОтключитьОбработчикОповещения','DetachNotificationHandler',
        'ПолучитьСообщенияПользователю','GetUserMessages',
        'ПараметрыДоступа','AccessParameters',
        'ПредставлениеПриложения','ApplicationPresentation',
        'ТекущийЯзыкСистемы','CurrentSystemLanguage',
        'ЗапуститьСистему','RunSystem',
        'ТекущийРежимЗапуска','CurrentRunMode',
        'УстановитьЧасовойПоясСеанса','SetSessionTimeZone',
        'ЧасовойПоясСеанса','SessionTimeZone',
        'ТекущаяДатаСеанса','CurrentSessionDate',
        'УстановитьКраткийЗаголовокПриложения','SetShortApplicationCaption',
        'ПолучитьКраткийЗаголовокПриложения','GetShortApplicationCaption',
        'ПредставлениеПрава','RightPresentation',
        'ВыполнитьПроверкуПравДоступа','VerifyAccessRights',
        'РабочийКаталогДанныхПользователя','UserDataWorkDir',
        'КаталогДокументов','DocumentsDir',
        'ПолучитьИнформациюЭкрановКлиента','GetClientDisplaysInformation',
        'ТекущийВариантОсновногоШрифтаКлиентскогоПриложения','ClientApplicationBaseFontCurrentVariant',
        'ТекущийВариантИнтерфейсаКлиентскогоПриложения','ClientApplicationInterfaceCurrentVariant',
        'УстановитьЗаголовокКлиентскогоПриложения','SetClientApplicationCaption',
        'ПолучитьЗаголовокКлиентскогоПриложения','GetClientApplicationCaption',
        'НачатьПолучениеКаталогаВременныхФайлов','BeginGettingTempFilesDir',
        'НачатьПолучениеКаталогаДокументов','BeginGettingDocumentsDir',
        'НачатьПолучениеРабочегоКаталогаДанныхПользователя','BeginGettingUserDataWorkDir',
        'ПодключитьОбработчикЗапросаНастроекКлиентаЛицензирования','AttachLicensingClientParametersRequestHandler',
        'ОтключитьОбработчикЗапросаНастроекКлиентаЛицензирования','DetachLicensingClientParametersRequestHandler',
        # Глобальный контекст - процедуры и функции сохранения значений
        'ЗначениеВСтрокуВнутр','ValueToStringInternal',
        'ЗначениеИзСтрокиВнутр','ValueFromStringInternal',
        'ЗначениеВФайл','ValueToFile',
        'ЗначениеИзФайла','ValueFromFile',
        # Глобальный контекст - Процедуры и функции работы с операционной системой
        'КомандаСистемы','System',
        'ЗапуститьПриложение','RunApp',
        'ПолучитьCOMОбъект','GetCOMObject',
        'ПользователиОС','OSUsers',
        'НачатьЗапускПриложения','BeginRunningApplication',
        # Глобальный контекст - Процедуры и функции работы с внешними компонентами
        'ПодключитьВнешнююКомпоненту','AttachAddIn',
        'НачатьУстановкуВнешнейКомпоненты','BeginInstallAddIn',
        'УстановитьВнешнююКомпоненту','InstallAddIn',
        'НачатьПодключениеВнешнейКомпоненты','BeginAttachingAddIn',
        # Глобальный контекст - Процедуры и функции работы с файлами
        'КопироватьФайл','FileCopy',
        'ПереместитьФайл','MoveFile',
        'УдалитьФайлы','DeleteFiles',
        'НайтиФайлы','FindFiles',
        'СоздатьКаталог','CreateDirectory',
        'ПолучитьИмяВременногоФайла','GetTempFileName',
        'РазделитьФайл','SplitFile',
        'ОбъединитьФайлы','MergeFiles',
        'ПолучитьФайл','GetFile',
        'НачатьПомещениеФайла','BeginPutFile',
        'ПоместитьФайл','PutFile',
        'ЭтоАдресВременногоХранилища','IsTempStorageURL',
        'УдалитьИзВременногоХранилища','DeleteFromTempStorage',
        'ПолучитьИзВременногоХранилища','GetFromTempStorage',
        'ПоместитьВоВременноеХранилище','PutToTempStorage',
        'ПодключитьРасширениеРаботыСФайлами','AttachFileSystemExtension',
        'НачатьУстановкуРасширенияРаботыСФайлами','BeginInstallFileSystemExtension',
        'УстановитьРасширениеРаботыСФайлами','InstallFileSystemExtension',
        'ПолучитьФайлы','GetFiles',
        'ПоместитьФайлы','PutFiles',
        'ЗапроситьРазрешениеПользователя','RequestUserPermission',
        'ПолучитьМаскуВсеФайлы','GetAllFilesMask',
        'ПолучитьМаскуВсеФайлыКлиента','GetClientAllFilesMask',
        'ПолучитьМаскуВсеФайлыСервера','GetServerAllFilesMask',
        'ПолучитьРазделительПути','GetPathSeparator',
        'ПолучитьРазделительПутиКлиента','GetClientPathSeparator',
        'ПолучитьРазделительПутиСервера','GetServerPathSeparator',
        'НачатьПодключениеРасширенияРаботыСФайлами','BeginAttachingFileSystemExtension',
        'НачатьЗапросРазрешенияПользователя','BeginRequestingUserPermission',
        'НачатьПоискФайлов','BeginFindingFiles',
        'НачатьСозданиеКаталога','BeginCreatingDirectory',
        'НачатьКопированиеФайла','BeginCopyingFile',
        'НачатьПеремещениеФайла','BeginMovingFile',
        'НачатьУдалениеФайлов','BeginDeletingFiles',
        'НачатьПолучениеФайлов','BeginGettingFiles',
        'НачатьПомещениеФайлов','BeginPuttingFiles',
        # Глобальный контекст - Процедуры и функции работы с информационной базой
        'НачатьТранзакцию','BeginTransaction',
        'ЗафиксироватьТранзакцию','CommitTransaction',
        'ОтменитьТранзакцию','RollbackTransaction',
        'УстановитьМонопольныйРежим','SetExclusiveMode',
        'МонопольныйРежим','ExclusiveMode',
        'ПолучитьОперативнуюОтметкуВремени','GetRealTimeTimestamp',
        'ПолучитьСоединенияИнформационнойБазы','GetInfoBaseConnections',
        'НомерСоединенияИнформационнойБазы','InfoBaseConnectionNumber',
        'КонфигурацияИзменена','ConfigurationChanged',
        'КонфигурацияБазыДанныхИзмененаДинамически','DataBaseConfigurationChangedDynamically',
        'УстановитьВремяОжиданияБлокировкиДанных','SetLockWaitTime',
        'ОбновитьНумерациюОбъектов','RefreshObjectsNumbering',
        'ПолучитьВремяОжиданияБлокировкиДанных','GetLockWaitTime',
        'КодЛокализацииИнформационнойБазы','InfoBaseLocaleCode',
        'УстановитьМинимальнуюДлинуПаролейПользователей','SetUserPasswordMinLength',
        'ПолучитьМинимальнуюДлинуПаролейПользователей','GetUserPasswordMinLength',
        'ИнициализироватьПредопределенныеДанные','InitializePredefinedData',
        'УдалитьДанныеИнформационнойБазы','EraseInfoBaseData',
        'УстановитьПроверкуСложностиПаролейПользователей','SetUserPasswordStrengthCheck',
        'ПолучитьПроверкуСложностиПаролейПользователей','GetUserPasswordStrengthCheck',
        'ПолучитьСтруктуруХраненияБазыДанных','GetDBStorageStructureInfo',
        'УстановитьПривилегированныйРежим','SetPrivilegedMode',
        'ПривилегированныйРежим','PrivilegedMode',
        'ТранзакцияАктивна','TransactionActive',
        'НеобходимостьЗавершенияСоединения','ConnectionStopRequest',
        'НомерСеансаИнформационнойБазы','InfoBaseSessionNumber',
        'ПолучитьСеансыИнформационнойБазы','GetInfoBaseSessions',
        'ЗаблокироватьДанныеДляРедактирования','LockDataForEdit',
        'УстановитьСоединениеСВнешнимИсточникомДанных','ConnectExternalDataSource',
        'РазблокироватьДанныеДляРедактирования','UnlockDataForEdit',
        'РазорватьСоединениеСВнешнимИсточникомДанных','DisconnectExternalDataSource',
        'ПолучитьБлокировкуСеансов','GetSessionsLock',
        'УстановитьБлокировкуСеансов','SetSessionsLock',
        'ОбновитьПовторноИспользуемыеЗначения','RefreshReusableValues',
        'УстановитьБезопасныйРежим','SetSafeMode',
        'БезопасныйРежим','SafeMode',
        'ПолучитьДанныеВыбора','GetChoiceData',
        'УстановитьЧасовойПоясИнформационнойБазы','SetInfoBaseTimeZone',
        'ПолучитьЧасовойПоясИнформационнойБазы','GetInfoBaseTimeZone',
        'ПолучитьОбновлениеКонфигурацииБазыДанных','GetDataBaseConfigurationUpdate',
        'УстановитьБезопасныйРежимРазделенияДанных','SetDataSeparationSafeMode',
        'БезопасныйРежимРазделенияДанных','DataSeparationSafeMode',
        'УстановитьВремяЗасыпанияПассивногоСеанса','SetPassiveSessionHibernateTime',
        'ПолучитьВремяЗасыпанияПассивногоСеанса','GetPassiveSessionHibernateTime',
        'УстановитьВремяЗавершенияСпящегоСеанса','SetHibernateSessionTerminateTime',
        'ПолучитьВремяЗавершенияСпящегоСеанса','GetHibernateSessionTerminateTime',
        'ПолучитьТекущийСеансИнформационнойБазы','GetCurrentInfoBaseSession',
        'ПолучитьИдентификаторКонфигурации','GetConfigurationID',
        'УстановитьНастройкиКлиентаЛицензирования','SetLicensingClientParameters',
        'ПолучитьИмяКлиентаЛицензирования','GetLicensingClientName',
        'ПолучитьДополнительныйПараметрКлиентаЛицензирования','GetLicensingClientAdditionalParameter',
        # Глобальный контекст - Процедуры и функции работы с данными информационной базы
        'НайтиПомеченныеНаУдаление','FindMarkedForDeletion',
        'НайтиПоСсылкам','FindByRef',
        'УдалитьОбъекты','DeleteObjects',
        'УстановитьОбновлениеПредопределенныхДанныхИнформационнойБазы','SetInfoBasePredefinedDataUpdate',
        'ПолучитьОбновлениеПредопределенныхДанныхИнформационнойБазы','GetInfoBasePredefinedData',
        # Глобальный контекст - Процедуры и функции работы с XML
        'XMLСтрока','XMLString',
        'XMLЗначение','XMLValue',
        'XMLТип','XMLType',
        'XMLТипЗнч','XMLTypeOf',
        'ИзXMLТипа','FromXMLType',
        'ВозможностьЧтенияXML','CanReadXML',
        'ПолучитьXMLТип','GetXMLType',
        'ПрочитатьXML','ReadXML',
        'ЗаписатьXML','WriteXML',
        'НайтиНедопустимыеСимволыXML','FindDisallowedXMLCharacters',
        'ИмпортМоделиXDTO','ImportXDTOModel',
        'СоздатьФабрикуXDTO','CreateXDTOFactory',
        # Глобальный контекст - Процедуры и функции работы с JSON
        'ЗаписатьJSON','WriteJSON',
        'ПрочитатьJSON','ReadJSON',
        'ПрочитатьДатуJSON','ReadJSONDate',
        'ЗаписатьДатуJSON','WriteJSONDate',
        # Глобальный контекст - Процедуры и функции работы с журналом регистрации
        'ЗаписьЖурналаРегистрации','WriteLogEvent',
        'ПолучитьИспользованиеЖурналаРегистрации','GetEventLogUsing',
        'УстановитьИспользованиеЖурналаРегистрации','SetEventLogUsing',
        'ПредставлениеСобытияЖурналаРегистрации','EventLogEventPresentation',
        'ВыгрузитьЖурналРегистрации','UnloadEventLog',
        'ПолучитьЗначенияОтбораЖурналаРегистрации','GetEventLogFilterValues',
        'УстановитьИспользованиеСобытияЖурналаРегистрации','SetEventLogEventUse',
        'ПолучитьИспользованиеСобытияЖурналаРегистрации','GetEventLogEventUse',
        'СкопироватьЖурналРегистрации','CopyEventLog',
        'ОчиститьЖурналРегистрации','ClearEventLog',
        # Глобальный контекст - Процедуры и функции работы с универсальными объектами
        'ЗначениеВДанныеФормы','ValueToFormData',
        'ДанныеФормыВЗначение','FormDataToValue',
        'КопироватьДанныеФормы','CopyFormData',
        'УстановитьСоответствиеОбъектаИФормы','SetObjectAndFormConformity',
        'ПолучитьСоответствиеОбъектаИФормы','GetObjectAndFormConformity',
        # Глобальный контекст - Процедуры и функции работы с функциональными опциями
        'ПолучитьФункциональнуюОпцию','GetFunctionalOption',
        'ПолучитьФункциональнуюОпциюИнтерфейса','GetInterfaceFunctionalOption',
        'УстановитьПараметрыФункциональныхОпцийИнтерфейса','SetInterfaceFunctionalOptionParameters',
        'ПолучитьПараметрыФункциональныхОпцийИнтерфейса','GetInterfaceFunctionalOptionParameters',
        'ОбновитьИнтерфейс','RefreshInterface',
        # Глобальный контекст - Процедуры и функции работы с криптографией
        'УстановитьРасширениеРаботыСКриптографией','InstallCryptoExtension',
        'НачатьУстановкуРасширенияРаботыСКриптографией','BeginInstallCryptoExtension',
        'ПодключитьРасширениеРаботыСКриптографией','AttachCryptoExtension',
        'НачатьПодключениеРасширенияРаботыСКриптографией','BeginAttachingCryptoExtension',
        # Глобальный контекст - Процедуры и функции работы со стандартным интерфейсом OData
        'УстановитьСоставСтандартногоИнтерфейсаOData','SetStandardODataInterfaceContent',
        'ПолучитьСоставСтандартногоИнтерфейсаOData','GetStandardODataInterfaceContent',
        # Глобальный контекст - Процедуры и функции работы с двоичными данными
        'СоединитьБуферыДвоичныхДанных','ConcatBinaryDataBuffers'
        # Глобальный контекст - Прочие процедуры и функции
        'Мин','Min',
        'Макс','Max',
        'ОписаниеОшибки','ErrorDescription',
        'Вычислить','Eval',
        'ИнформацияОбОшибке','ErrorInfo',
        'Base64Значение','Base64Value',
        'Base64Строка','Base64String',
        'ЗаполнитьЗначенияСвойств','FillPropertyValues',
        'ЗначениеЗаполнено','ValueIsFilled',
        'ПолучитьПредставленияНавигационныхСсылок','GetURLsPresentations',
        'НайтиОкноПоНавигационнойСсылке','FindWindowByURL',
        'ПолучитьОкна','GetWindows',
        'ПерейтиПоНавигационнойСсылке','GotoURL',
        'ПолучитьНавигационнуюСсылку','GetURL',
        'ПолучитьДопустимыеКодыЛокализации','GetAvailableLocaleCodes',
        'ПолучитьНавигационнуюСсылкуИнформационнойБазы','GetInfoBaseURL',
        'ПредставлениеКодаЛокализации','LocaleCodePresentation',
        'ПолучитьДопустимыеЧасовыеПояса','GetAvailableTimeZones',
        'ПредставлениеЧасовогоПояса','TimeZonePresentation',
        'ТекущаяУниверсальнаяДата','CurrentUniversalDate',
        'ТекущаяУниверсальнаяДатаВМиллисекундах','CurrentUniversalDateInMilliseconds',
        'МестноеВремя','ToLocalTime',
        'УниверсальноеВремя','ToUniversalTime',
        'ЧасовойПояс','TimeZone',
        'СмещениеЛетнегоВремени','DaylightTimeOffset',
        'СмещениеСтандартногоВремени','StandardTimeOffset',
        'КодироватьСтроку','EncodeString',
        'РаскодироватьСтроку','DecodeString',
        'Найти','Find',
        # Глобальный контекст - События приложения и сеанса
        'ПередНачаломРаботыСистемы','BeforeStart',
        'ПриНачалеРаботыСистемы','OnStart',
        'ПередЗавершениемРаботыСистемы','BeforeExit',
        'ПриЗавершенииРаботыСистемы','OnExit',
        'ОбработкаВнешнегоСобытия','ExternEventProcessing',
        'УстановкаПараметровСеанса','SessionParametersSetting',
        'ПриИзмененииПараметровЭкрана','OnChangeDisplaySettings',
    ), prefix='(?<!\.)', suffix=r'(?=(\s?[\(])|$)(?=[^\wа-яё]|$)')

    NAME_CLASS = words((
        # support.class.bsl
        # Глобальный контекст - Свойства (классы)
        'WSСсылки','WSReferences',
        'БиблиотекаКартинок','PictureLib',
        'БиблиотекаМакетовОформленияКомпоновкиДанных','DataCompositionAppearanceTemplateLib',
        'БиблиотекаСтилей','StyleLib',
        'БизнесПроцессы','BusinessProcesses',
        'ВнешниеИсточникиДанных','ExternalDataSources',
        'ВнешниеОбработки','ExternalDataProcessors',
        'ВнешниеОтчеты','ExternalReports',
        'Документы','Documents',
        'ДоставляемыеУведомления','DeliverableNotifications',
        'ЖурналыДокументов','DocumentJournals',
        'Задачи','Tasks',
        'ИспользованиеРабочейДаты','WorkingDateUse',
        'ИсторияРаботыПользователя','UserWorkHistory',
        'Константы','Constants',
        'КритерииОтбора','FilterCriteria',
        'Метаданные','Metadata',
        'Обработки','DataProcessors',
        'ОтправкаДоставляемыхУведомлений','DeliverableNotificationSend',
        'Отчеты','Reports',
        'ПараметрыСеанса','SessionParameters',
        'Перечисления','Enums',
        'ПланыВидовРасчета','ChartsOfCalculationTypes',
        'ПланыВидовХарактеристик','ChartsOfCharacteristicTypes',
        'ПланыОбмена','ExchangePlans',
        'ПланыСчетов','ChartsOfAccounts',
        'ПолнотекстовыйПоиск','FullTextSearch',
        'ПользователиИнформационнойБазы','InfoBaseUsers',
        'Последовательности','Sequences',
        'РасширенияКонфигурации','ConfigurationExtensions',
        'РегистрыБухгалтерии','AccountingRegisters',
        'РегистрыНакопления','AccumulationRegisters',
        'РегистрыРасчета','CalculationRegisters',
        'РегистрыСведений','InformationRegisters',
        'РегламентныеЗадания','ScheduledJobs',
        'СериализаторXDTO','XDTOSerializer',
        'Справочники','Catalogs',
        'СредстваГеопозиционирования','LocationTools',
        'СредстваКриптографии','CryptoToolsManager',
        'СредстваМультимедиа','MultimediaTools',
        'СредстваПочты','MailTools',
        'СредстваТелефонии','TelephonyTools',
        'ФабрикаXDTO','XDTOFactory',
        'ФоновыеЗадания','BackgroundJobs',
        'ХранилищаНастроек','SettingsStorages',
        'ВстроенныеПокупки','InAppPurchases',
        'ОтображениеРекламы','AdRepresentation',
        'ПанельЗадачОС','OSTaskbar',
        'ПроверкаВстроенныхПокупок','InAppPurchasesValidation'
        ,'ТаблицаЗначений','TableOfValues'
        # support.variable.bsl
        # Глобальный контекст - Свойства (переменные)
        'ГлавныйИнтерфейс','MainInterface',
        'ГлавныйСтиль','MainStyle',
        'ПараметрЗапуска','LaunchParameter',
        'РабочаяДата','WorkingDate',
        'ХранилищеВариантовОтчетов','ReportsVariantsStorage',
        'ХранилищеНастроекДанныхФорм','FormDataSettingsStorage',
        'ХранилищеОбщихНастроек','CommonSettingsStorage',
        'ХранилищеПользовательскихНастроекДинамическихСписков','DynamicListsUserSettingsStorage',
        'ХранилищеПользовательскихНастроекОтчетов','ReportsUserSettingsStorage',
        'ХранилищеСистемныхНастроек','SystemSettingsStorage'
    ), prefix='(?<!\.)', suffix=r'\b')

    CONSTANT_NAMES = (
        # constant.language.bsl
        'Неопределено','Undefined','Истина','True','Ложь','False','NULL'
    )

    KEYWORD_CONSTANT = words(CONSTANT_NAMES, prefix='(?<!\.)', suffix=r'\b')

    KEYWORD_EXCEPTION = words((
        'ВызватьИсключение','Raise',
    ), prefix='(?<!\.)', suffix=r'\b')

    KEYWORD_EXCEPTION_CALL = words((
        'ВызватьИсключение','Raise',
    ), prefix='(?<!\.)', suffix=r'(?=(\s?[\(]))')

    # keywords that also used as function-like calls (treat as builtin when followed by '(')
    KEYWORD_AS_FUNCTION = words((
        'Новый','New',
    ), prefix='(?<!\.)', suffix=r'(?=(\s?[\(]))')

    OPERATORS = words((
        '=','<=','>=','<>','<','>','+','-','*','/','%','.'
    ))

    # see https://pygments.org/docs/tokens
    tokens = {
        'root': [
            (r'\n', Token.Text),
            (r'[^\S\n]+', Token.Text),
            (r'\/\/.*?(?=\n)', Token.Comment.Single),
            (r'\#(Если|If)\b', Token.Comment.Preproc, 'preproc_if'),
            (r'\#(ИначеЕсли|ElsIf)\b', Token.Comment.Preproc, 'preproc_if'),
            (r'\#(Иначе|Else|КонецЕсли|EndIf|Область|Region|КонецОбласти|EndRegion|Вставка|Insert|КонецВставки|EndInsert|Удаление|Delete|КонецУдаления|EndDelete)\b.*', Token.Comment.Preproc),
            # decorator with quoted name: split into decorator, punctuation and inner name
            (r'(&[\wа-яё_][\wа-яё0-9_]*)\s*(\()\s*"([^"]*)"\s*(\))',
             bygroups(Token.Name.Decorator, Token.Punctuation, Token.Name.Function, Token.Punctuation)),
            # decorator with parameters: split decorator and parse parameters
            (r'(&[\wа-яё_][\wа-яё0-9_]*)\s*(\()', bygroups(Token.Name.Decorator, Token.Punctuation), 'decorator_params'),
            (r'[\[\]:(),;]', Token.Punctuation),
            (r'\&.*$', Token.Name.Decorator),
            (r'\b(Процедура|Функция|Procedure|Function)\b(\s+)([\wа-яё_][\wа-яё0-9_]*)\s*(\()',
             bygroups(Token.Keyword, Token.Text, Token.Name.Function, Token.Punctuation), 'params'),
            (OPERATORS, Token.Operator),
            (r'\#.*$', Token.Comment.Preproc),
            # match forbidden-constant calls like Неопределено(....) as a single error token
            (r'\b(?:' + '|'.join(CONSTANT_NAMES) + r')\b\s*\([^\)]*\)', Token.Generic.Error),
            (NAME_BUILTIN, Token.Name.Builtin),
            (KEYWORD_DECLARATION, Token.Keyword.Declaration),
            (KEYWORD_EXCEPTION_CALL, Token.Name.Exception),
            (KEYWORD_AS_FUNCTION, Token.Name.Builtin),
            (KEYWORD_EXCEPTION, Token.Name.Exception),
            (KEYWORD, Token.Keyword),
            (NAME_CLASS, Token.Name.Class),
            (KEYWORD_CONSTANT, Token.Keyword.Constant),
            (r'[\wа-яё_][\wа-яё0-9_]*(?=(\s?[\(]))', Token.Name.Function),
            (r'\b\d+\.?\d*\b', Token.Literal.Number),
            (r'[\wа-яё_][\wа-яё0-9_]*', Token.Name.Variable),
            (r'"(?=[^"]*\b(ВЫБРАТЬ|SELECT)\b)', Token.Literal.String, 'query_string'),
            ('\"', Token.String, 'string'),
            (r'\'.*?\'', Token.Literal.Date),
            (r'~.*?(?=[:;])', Token.Name.Label),
        ],
        'preproc_if': [
            (r'\n', Token.Text, '#pop'),
            (r'\b(Сервер|НаСервере|Клиент|НаКлиенте|ТонкийКлиент|МобильныйКлиент|ВебКлиент|ВнешнееСоединение|ТолстыйКлиентУправляемоеПриложение|ТолстыйКлиентОбычноеПриложение|МобильныйАвтономныйСервер|МобильноеПриложениеКлиент|МобильноеПриложениеСервер)\b', Token.Keyword.Constant),
            (r'\b(И|Или|НЕ|Then|Тогда|And|Or|Not)\b', Token.Comment.Preproc),
            (r'\#', Token.Comment.Preproc),
            (r'[^\S\n]+', Token.Text),
            (r'[^\s#]+', Token.Comment.Preproc),
        ],
        'string': [
            ('\"(?![\"])', Token.String, '#pop'),
            (r'\n', Token.Text),
            (r'(?<=\n)[^\S\n]+', Token.Text),
            (r'(?<=[^\S\n])\/\/.*?(?=\n)', Token.Comment.Single),
            (r'(?<=^)\/\/.*?(?=\n)', Token.Comment.Single),
            (r'\|', Token.String),
            (r'\"\"', Token.String.Escape),
            (r'%%', Token.String.Escape),
            (r'%\d', Token.String.Interpol),
            (r'%', Token.Literal.String),
            (r'[^\"\|\n%]+', Token.String),
        ],
        'query_string': [
            (r'""', Token.Literal.String.Escape),
            (r'"', Token.Literal.String, '#pop'),
            # Delay instantiation to avoid forward reference issues and keep formatter options
            (r'[^"]+', using(lambda **kwargs: SdblQueryLexer(**kwargs))),
        ],
        'decorator_params': [
            (r'\)', Token.Punctuation, '#pop'),
            (r'\n', Token.Text),
            (r'[^\S\n]+', Token.Text),
            (r',', Token.Operator),
            (r'=', Token.Operator),
            (r'"[^"]*"', Token.Literal.String),
            (r'(\b[A-Za-zА-Яа-яёЁ_][\wа-яё0-9_]*\b)(\s*)(=)(\s*)(?!Неопределено\b|Undefined\b|Null\b|Истина\b|True\b|Ложь\b|False\b)([A-Za-zА-Яа-яёЁ_][\wа-яё0-9_]*)',
             bygroups(Token.Name.Variable, Token.Text, Token.Operator, Token.Text, Token.Generic.Error)),
            (r'([A-Za-zА-Яа-яёЁ_][\wа-яё0-9_]*)', Token.Name.Variable),
            (r'\b\d+\.?\d*\b', Token.Literal.Number),
            (r'"(?=[^"]*\b(ВЫБРАТЬ|SELECT)\b)', Token.Literal.String, 'query_string'),
            (r'.', Token.Text),
        ],
        'params': [
            (r'\)', Token.Punctuation, '#pop'),
            (r'\n', Token.Text),
            (r'[^\S\n]+', Token.Text),
            (r'\,', Token.Punctuation),
            (r'(&[\wа-яё_][\wа-яё0-9_]*)\s*(\()', bygroups(Token.Name.Decorator, Token.Punctuation), 'decorator_params'),
            (r'\&[^\s,(]+', Token.Name.Decorator),
            (r'\bЗнач\b|\bVal\b', Token.Keyword),
            (KEYWORD_CONSTANT, Token.Keyword.Constant),
            (r'(\b[A-Za-zА-Яа-яёЁ_][\wа-яё0-9_]*\b)(\s*)(=)(\s*)(?!Неопределено\b|Undefined\b|Null\b|Истина\b|True\b|Ложь\b|False\b)([A-Za-zА-Яа-яёЁ_][\wа-яё0-9_]*)',
             bygroups(Token.Name.Variable, Token.Text, Token.Operator, Token.Text, Token.Generic.Error)),
            (r'([A-Za-zА-Яа-яёЁ_][\wа-яё0-9_]*)', Token.Name.Variable),
            (r'=', Token.Operator),
            (r'\b\d+\.?\d*\b', Token.Literal.Number),
            (r'"(?=[^"]*\b(ВЫБРАТЬ|SELECT)\b)', Token.Literal.String, 'query_string'),
            (r'.', Token.Text),
        ],
        # String.Regex
    }




class SdblLexer(RegexLexer):
    name = '1C (SDBL) Lexer'
    aliases = ['sdbl']
    filenames = ['*.sdbl']

    flags = re.MULTILINE | re.IGNORECASE | re.VERBOSE

    KEYWORD_DECLARATION = words((
        'ДЛЯ ИЗМЕНЕНИЯ','FOR UPDATE',
        'ИТОГИ ПО','TOTALS BY',
        'ИНДЕКСИРОВАТЬ ПО','INDEX BY','ИНДЕКСИРОВАТЬ ПО НАБОРАМ','INDEX BY SETS',
        'СГРУППИРОВАТЬ ПО','GROUP BY',
        'СОЕДИНЕНИЕ ПО','JOIN ON',
        'УПОРЯДОЧИТЬ ПО','ORDER BY',
        'АВТОНОМЕРЗАПИСИ','RECORDAUTONUMBER',
        'АВТОУПОРЯДОЧИВАНИЕ','AUTOORDER',
        'БУЛЕВО','BOOLEAN',
        'В','IN',
        'ВНЕШНЕЕ','OUTER',
        'ВНУТРЕННЕЕ','INNER',
        'ВОЗР','ASC',
        'ВСЕ','ALL',
        'ВЫБОР','CASE',
        'ВЫБРАТЬ','SELECT',
        'ВЫРАЗИТЬ','CAST',
        'ГДЕ','WHERE',
        'ГОД','YEAR',
        'ГРУППИРУЮЩИМ','GROUPING',
        'ДАТА','DATE',
        'ДАТАВРЕМЯ','DATETIME',
        'ДЕКАДА','TENDAYS',
        'ДЕНЬ','DAY',
        'ДЕНЬГОДА','DAYOFYEAR',
        'ДЕНЬНЕДЕЛИ','WEEKDAY',
        'ДЛЯ','FOR',
        'ДОБАВИТЬ','ADD',
        'ДОБАВИТЬКДАТЕ','DATEADD',
        'ЕСТЬ','IS',
        'ЕСТЬNULL','ISNULL',
        'Значение','VALUE',
        'И','AND',
        'ИЕРАРХИИ','HIERARCHY',
        'ИЕРАРХИЯ','HIERARCHY',
        'ИЗ','FROM',
        'ИЗМЕНЕНИЯ','UPDATE',
        'ИЛИ','OR',
        'ИМЕЮЩИЕ','HAVING',
        'ИНАЧЕ','ELSE',
        'ИНДЕКСИРОВАТЬ','INDEX',
        'ИТОГИ','TOTALS',
        'КАК','AS',
        'КВАРТАЛ','QUARTER',
        'КОГДА','WHEN',
        'КОЛИЧЕСТВО','COUNT',
        'КОНЕЦ','END',
        'КОНЕЦПЕРИОДА','ENDOFPERIOD',
        'ЛЕВОЕ','LEFT',
        'МАКСИМУМ','MAX',
        'МЕЖДУ','BETWEEN',
        'МЕСЯЦ','MONTH',
        'МИНИМУМ','MIN',
        'МИНУТА','MINUTE',
        'НАБОРАМ','SETS',
        'НАЧАЛОПЕРИОДА','BEGINOFPERIOD',
        'НЕ','NOT',
        'НЕДЕЛЯ','WEEK',
        'ОБЩИЕ','OVERALL',
        'ОБЪЕДИНИТЬ','UNION',
        'ПЕРВЫЕ','TOP',
        'ПЕРИОДАМИ','PERIODS',
        'ПО','BY','ON',
        'ПОДОБНО','LIKE',
        'ПОДСТРОКА','SUBSTRING',
        'ПОЛНОЕ','FULL',
        'ПОЛУГОДИЕ','HALFYEAR',
        'ПОМЕСТИТЬ','INTO',
        'ПРАВОЕ','RIGHT',
        'ПРЕДСТАВЛЕНИЕ','PRESENTATION',
        'ПРЕДСТАВЛЕНИЕССЫЛКИ','REFPRESENTATION',
        'ПУСТАЯТАБЛИЦА','EMPTYTABLE',
        'РАЗЛИЧНЫЕ','DISTINCT',
        'РАЗНОСТЬДАТ','DATEDIFF',
        'РАЗРЕШЕННЫЕ','ALLOWED',
        'СГРУППИРОВАТЬ','GROUP',
        'СГРУППИРОВАНОПО','GROUPEDBY',
        'СЕКУНДА','SECOND',
        'СЕКУНДА','SECOND',
        'СОЕДИНЕНИЕ','JOIN',
        'СПЕЦСИМВОЛ','ESCAPE',
        'СРЕДНЕЕ','AVG',
        'ССЫЛКА','REFS',
        'СТРОКА','STRING',
        'СУММА','SUM',
        'ТИП','TYPE',
        'ТИПЗНАЧЕНИЯ','VALUETYPE',
        'ТОГДА','THEN',
        'ТОЛЬКО','ONLY',
        'УБЫВ','DESC',
        'УНИКАЛЬНО','UNIQUE',
        'УНИКАЛЬНЫЙИДЕНТИФИКАТОР','UUID',
        'УНИЧТОЖИТЬ','DROP',
        'УПОРЯДОЧИТЬ','ORDER',
        'ЧАС','HOUR',
        'ЧИСЛО','NUMBER',
    ), prefix='(?<!\.)', suffix=r'\b')
    
    KEYWORD_CONSTANT = words((
        # constant.language.sdbl
        'НЕОПРЕДЕЛЕНО','UNDEFINED','Истина','True','Ложь','False','NULL'
    ), prefix='(?<!\.)', suffix=r'\b')

    FUNCTION_CALL = words((
        'ГОД','YEAR',
        'ДАТАВРЕМЯ','DATETIME',
        'ВЫРАЗИТЬ','CAST',
        'ДАТА','DATE',
        'ДОБАВИТЬКДАТЕ','DATEADD',
        'РАЗНОСТЬДАТ','DATEDIFF',
        'АВТОНОМЕРЗАПИСИ','RECORDAUTONUMBER',
        'ПОДСТРОКА','SUBSTRING','СТРОКА','STRING',
        'ДлинаСтроки',
        'СокрЛ','СокрП','СокрЛП',
        'Лев','Прав','СтрНайти','ВРег','НРег','СтрЗаменить',
        'ACOS','ASIN','ATAN','COS','TAN','SIN','EXP','LOG','LOG10','POW','SQRT','ОКР','ЦЕЛ',
        'СУММА','SUM','МИНИМУМ','MIN','МАКСИМУМ','MAX','СРЕДНЕЕ','AVG','КОЛИЧЕСТВО','COUNT',
        'ТИП','TYPE','ТИПЗНАЧЕНИЯ','VALUETYPE',
        'НАЧАЛОПЕРИОДА','BEGINOFPERIOD','КОНЕЦПЕРИОДА','ENDOFPERIOD',
        'ДЕНЬ','DAY','ДЕНЬГОДА','DAYOFYEAR','ДЕНЬНЕДЕЛИ','WEEKDAY',
        'МЕСЯЦ','MONTH','КВАРТАЛ','QUARTER','НЕДЕЛЯ','WEEK','ДЕКАДА','TENDAYS',
        'СЕКУНДА','SECOND','МИНУТА','MINUTE','ЧАС','HOUR',
        'ДОБАВИТЬ','ADD','ИНДЕКСИРОВАТЬ ПО НАБОРАМ','INDEX BY SETS',
        'ПРЕДСТАВЛЕНИЕ','PRESENTATION','ПРЕДСТАВЛЕНИЕССЫЛКИ','REFPRESENTATION',
        'ЕСТЬNULL','ISNULL','СГРУППИРОВАНОПО','GROUPEDBY','РАЗМЕРХРАНИМЫХДАННЫХ','УНИКАЛЬНЫЙИДЕНТИФИКАТОР','UUID',
    ), prefix='(?<!\.)', suffix=r'(?=(\s?[\(]))')

    OPERATORS = r'(<=|>=|<>|=|<|>|\+|-|\*|\/|\.)'

    tokens = {
        'root': [
            (r'\n', Token.Text),
            (r'[^\S\n]+', Token.Text),
            (r'\/\/.*?(?=\n)', Token.Comment.Single),
            (r'\|', Token.Generic.Error),
            (r'(&[A-Za-zА-Яа-яЁё_][\wа-яё0-9_]*)', Token.Name.Constant),
            (OPERATORS, Token.Operator),
            (r'(?<=\bКАК\s)Ссылка\b', Token.Name.Variable),
            (r'(?<=\.)[A-Za-zА-Яа-яЁё_][\wа-яё0-9_]*', Token.Name.Variable),
            (r'[\[\]:(),;]', Token.Punctuation),
            (FUNCTION_CALL, Token.Name.Builtin),
            (KEYWORD_DECLARATION, Token.Keyword.Declaration),
            (KEYWORD_CONSTANT, Token.Keyword.Constant),
            (r'\b\d+\.?\d*\b', Token.Literal.Number),
            (r'[\wа-яё_][\wа-яё0-9_]*', Token.Name.Variable),
            ('\"', Token.Literal.String, 'string'),
        ],
        'string': [
            ('\"(?![\"])', Token.Literal.String, '#pop'),
            (r'\n', Token.Text),
            (r'(?<=\n)[^\S\n]+', Token.Text),
            (r'(?<=[^\S\n])\/\/.*?(?=\n)', Token.Comment.Single),
            (r'(?<=^)\/\/.*?(?=\n)', Token.Comment.Single),
            (r'\"\"', Token.Literal.String.Escape),
            (r'\|', Token.Literal.String),
            (r'[^\"\n]+', Token.Literal.String),
        ]
    }


class SdblQueryLexer(SdblLexer):
    name = '1C (SDBL) Embedded Lexer'
    aliases = []

    tokens = copy.deepcopy(SdblLexer.tokens)
    _root_rules = tokens['root']
    for idx, rule in enumerate(_root_rules):
        if len(rule) >= 2 and rule[0] == r'\|' and rule[1] == Token.Generic.Error:
            _root_rules[idx] = (r'\|', Token.Literal.String)
            break
