#!/usr/bin/env python3
"""
Generate static Python data from 3rd_party JSON assets.

The JSON files stay in 3rd_party/, and this script converts them into
pygments_bsl/generated_data.py with tuples that the lexer imports at runtime.
"""

import json
import re
from pathlib import Path
from typing import Iterable, List

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "3rd_party"
OUT_FILE = ROOT / "pygments_bsl" / "generated_data.py"


def _unique(names: Iterable[str]) -> List[str]:
    seen = set()
    result = []
    for name in names:
        if name and name not in seen:
            seen.add(name)
            result.append(name)
    return result


def _load_names(filename: str) -> List[str]:
    data = json.loads((SRC_DIR / filename).read_text(encoding="utf-8"))
    names = []
    if isinstance(data, dict):
        names.extend(data.keys())
    else:
        for item in data:
            if isinstance(item, str):
                names.append(item)
            elif isinstance(item, dict):
                names.append(item.get("name"))
                names.append(item.get("name_en"))
    return _unique(names)


def _load_enum_names() -> List[str]:
    data = json.loads((SRC_DIR / "enums.json").read_text(encoding="utf-8"))
    names = []
    for item in data:
        if isinstance(item, dict):
            names.append(item.get("name"))
            names.append(item.get("name_en"))
    return _unique(names)


def _format_tuple(name: str, values: List[str]) -> str:
    body = "".join(f"    {value!r},\n" for value in values)
    return f"{name} = (\n{body})\n"


def main() -> None:
    type_names = [
        n
        for n in _load_names("types.json")
        if re.match(r"^[A-Za-zА-Яа-яЁё_][\wА-Яа-яЁё0-9]*$", n or "")
    ]

    content = (
        "# Auto-generated by tools/generate_data.py. Do not edit by hand.\n"
        "# Source data: 3rd_party/*.json\n\n"
        "__all__ = ['GLOBAL_METHOD_NAMES', 'GLOBAL_PROPERTY_NAMES', 'ENUM_PROPERTY_NAMES', 'TYPE_NAMES']\n\n"
        + _format_tuple("GLOBAL_METHOD_NAMES", _load_names("global-methods.json"))
        + "\n"
        + _format_tuple("GLOBAL_PROPERTY_NAMES", _load_names("global-properties.json"))
        + "\n"
        + _format_tuple("ENUM_PROPERTY_NAMES", _load_enum_names())
        + "\n"
        + _format_tuple("TYPE_NAMES", _unique(type_names))
    )

    OUT_FILE.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
