name: gh-pages

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        architecture: 'x64'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mkdocs mkdocs-material pygments-bsl

    - name: Build
      run: |
        mkdocs gh-deploy
